const { Toggle, Select, Input } = require("enquirer");
const fs = require("fs");
const os = require("os");
const { createLogger } = require("../utils/logger");
const { injectorConfig, cheatConfig } = require("../../../config.js");

const log = createLogger("SetupWizard");
/**
 * Setup Wizard for first-time configuration
 *
 * This module provides an interactive CLI wizard to help users create their
 * initial config.custom.js file if it doesn't exist.
 */
async function runSetupWizard(targetPath) {
    log.info("\n=============================");
    log.info("   Setup Wizard   ");
    log.info("=============================\n");
    log.info("It looks like this is your first time running the injector");
    log.info("Let's set up your basic configuration.\n");
    try {
        const isMac = os.platform() === "darwin";
        const platformChoices = isMac ? ["web"] : ["web", "steam"];
        const platformPrompt = new Select({
            name: "target",
            message: "Which platform do you want to use?",
            choices: platformChoices,
        });
        const target = await platformPrompt.run();

        // Prepare config objects
        const newInjectorConfig = { target };
        const newCheatConfig = {};
        if (target === "steam") {
            // Steam EXE Path
            const exePrompt = new Input({
                name: "gameExePath",
                message: "Path to LegendsOfIdleon.exe (leave empty for auto-detect):",
                initial: "",
            });
            newInjectorConfig.gameExePath = await exePrompt.run();
        } else {
            // Web URL
            const urlPrompt = new Input({
                name: "webUrl",
                message: "Idleon Web URL:",
                initial: injectorConfig.webUrl,
            });
            newInjectorConfig.webUrl = await urlPrompt.run();
            // Browser Path
            const browserPrompt = new Input({
                name: "browserPath",
                message: "Browser executable path (leave empty for auto-detect):",
                initial: "",
            });
            newInjectorConfig.browserPath = await browserPrompt.run();
        }
        // Enable In-Game UI
        const uiPrompt = new Toggle({
            message: "Enable In-Game UI Overlay?",
            enabled: "Yes",
            disabled: "No",
            initial: cheatConfig.ingameUI,
        });
        newCheatConfig.ingameUI = await uiPrompt.run();
        // Generate config.custom.js content
        const content = `/**
 * Custom Configuration Overrides
 * Generated by Setup Wizard on ${new Date().toDateString()}
 */
exports.injectorConfig = ${JSON.stringify(newInjectorConfig, null, 4)};
exports.cheatConfig = ${JSON.stringify(newCheatConfig, null, 4)};
`;
        fs.writeFileSync(targetPath, content, "utf8");
        log.info(`\nConfiguration saved to: ${targetPath}`);
        log.info("You can edit this file later to add startup cheats or more advanced settings.\n");
        return true;
    } catch {
        // Handle Ctrl+C or other interruptions
        log.warn("Setup cancelled. Using default configuration");
        return false;
    }
}
module.exports = { runSetupWizard };
